---
#
# Ansible managed
#

name: "Dependabot Merge"

on:
  pull_request:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true


jobs:
  dependabot_merge:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: Dependabot Auto Merge Action
        uses: buluma/dependabot-auto-merge-action@v2.1.1
