---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    branches:
      - master
      - main
      - testing
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '17 9 9 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "debian-systemd"
            tag: "latest"
          - image: "debian-systemd"
            tag: "bullseye"
          - image: "docker-ubuntu-systemd"
            tag: "latest"
          - image: "docker-ubuntu-systemd"
            tag: "focal"
          - image: "docker-ubuntu-systemd"
            tag: "bionic"
          - image: "kali"
            tag: "latest"
    steps:
      - name: Checkout Role
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: Running Molecule Test
        uses: buluma/molecule-action@v6.0.0
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
